// Generated from the official Morrowind, Tribunal, and Bloodmoon master files.
// Cell identity is case-insensitive interior name or exterior grid coordinates.
const officialInteriorCells = new Set([
  "abaelun mine",
  "abaesen-pulu egg mine",
  "abanabi",
  "abandoned shipwreck, cabin",
  "abandoned shipwreck, lower level",
  "abandoned shipwreck, upper level",
  "abebaal egg mine",
  "abernanit",
  "abinabi",
  "adanumuran",
  "addadshashanammu, shrine",
  "addamasartus",
  "ahallaraddon egg mine",
  "ahanibi-malmus egg mine",
  "aharasaplit camp, zallay's yurt",
  "aharnabi",
  "aharunartus",
  "ahemmusa camp, addammus's yurt",
  "ahemmusa camp, ashkhan's yurt",
  "ahemmusa camp, assamma-idan's yurt",
  "ahemmusa camp, dutadalk's yurt",
  "ahemmusa camp, kausi's yurt",
  "ahemmusa camp, lanabi's yurt",
  "ahemmusa camp, mamaea's yurt",
  "ahemmusa camp, nummu's yurt",
  "ahemmusa camp, wise woman's yurt",
  "ahinipalit",
  "aidanat camp, abassel's yurt",
  "ainab",
  "ainab, shrine",
  "ainat",
  "akimaes grotto",
  "akimaes-ilanipu egg mine",
  "akulakhan's chamber",
  "alas ancestral tomb",
  "ald daedroth, antechamber",
  "ald daedroth, inner shrine",
  "ald daedroth, left wing",
  "ald daedroth, outer shrine",
  "ald daedroth, right wing",
  "ald redaynia, tower",
  "ald sotha, lower level",
  "ald sotha, shrine",
  "ald sotha, upper level",
  "ald velothi, fevila bethrano's shack",
  "ald velothi, ganus lloryn's shack",
  "ald velothi, ienas arvel's shack",
  "ald velothi, lledsea relas's shack",
  "ald velothi, llerar vinden's shack",
  "ald velothi, outpost",
  "ald velothi, sathas rivul's shack",
  "ald velothi, vireveri darethran's shack",
  "ald-ruhn, ald skar inn",
  "ald-ruhn, arobar guard quarters",
  "ald-ruhn, arobar manor bedrooms",
  "ald-ruhn, arobar manor entrance",
  "ald-ruhn, arobar private quarters",
  "ald-ruhn, aryni orethi's house",
  "ald-ruhn, bevene releth: clothier",
  "ald-ruhn, bivale teneran: clothier",
  "ald-ruhn, boldrisa andrano's house",
  "ald-ruhn, braynas hlervu's house",
  "ald-ruhn, cienne sintieve: alchemist",
  "ald-ruhn, codus callonus: bookseller",
  "ald-ruhn, council club",
  "ald-ruhn, council hostel",
  "ald-ruhn, dandera selaro: smith",
  "ald-ruhn, daynes redothril: pawnbroker",
  "ald-ruhn, dravasa andrethi's house",
  "ald-ruhn, drinar varyon's house",
  "ald-ruhn, galsa gindu's house",
  "ald-ruhn, galthragoth's house",
  "ald-ruhn, gildan's house",
  "ald-ruhn, gindrala hleran's house",
  "ald-ruhn, goras andrelo's house",
  "ald-ruhn, guard tower 1",
  "ald-ruhn, guard tower 2",
  "ald-ruhn, guild of fighters",
  "ald-ruhn, guild of mages",
  "ald-ruhn, guls llervu's house",
  "ald-ruhn, hanarai assutlanipal's house",
  "ald-ruhn, ienas sarandas's house",
  "ald-ruhn, ilmiril's house",
  "ald-ruhn, llether vari: enchanter",
  "ald-ruhn, llethri guard quarters",
  "ald-ruhn, llethri manor bedrooms",
  "ald-ruhn, llethri manor entrance",
  "ald-ruhn, llethri private quarters",
  "ald-ruhn, malpenix blonia: trader",
  "ald-ruhn, manor district",
  "ald-ruhn, morag tong guildhall",
  "ald-ruhn, morvayn quarters",
  "ald-ruhn, pellecia aurrus's house",
  "ald-ruhn, practice room",
  "ald-ruhn, ramoran manor",
  "ald-ruhn, ramoran private quarters",
  "ald-ruhn, redoran council entrance",
  "ald-ruhn, redoran council hall",
  "ald-ruhn, sarethi guard quarters",
  "ald-ruhn, sarethi manor",
  "ald-ruhn, tauryon's house",
  "ald-ruhn, temple",
  "ald-ruhn, the rat in the pot",
  "ald-ruhn, tiras sadus: general merchandise",
  "ald-ruhn, tuveso beleth: smith",
  "ald-ruhn, venim manor bedrooms",
  "ald-ruhn, venim manor entrance",
  "ald-ruhn, venim manor guard quarters",
  "ald-ruhn, venim manor private quarters",
  "ald-ruhn, venim manor right wing",
  "aleft",
  "alen ancestral tomb",
  "almurbalarammi, shrine",
  "alof's farmhouse",
  "an abandoned shack",
  "ancient shipwreck, cabin",
  "ancient shipwreck, lower level",
  "ancient shipwreck, upper level",
  "andalen ancestral tomb",
  "andalor ancestral tomb",
  "andas ancestral tomb",
  "andasreth, lower level",
  "andasreth, propylon chamber",
  "andasreth, upper level",
  "andavel ancestral tomb",
  "andrano ancestral tomb",
  "andrethi ancestral tomb",
  "andules ancestral tomb",
  "ansi",
  "aralen ancestral tomb",
  "aran ancestral tomb",
  "arano ancestral tomb",
  "arano plantation",
  "arenim ancestral tomb",
  "arethan ancestral tomb",
  "arkngthand, cells of hollow hand",
  "arkngthand, deep ore passage",
  "arkngthand, hall of centrifuge",
  "arkngthand, heaven's gallery",
  "arkngthand, land's blood gallery",
  "arkngthand, weepingbell hall",
  "arkngthunch-sturdumz",
  "arrow, cabin",
  "arrow, lower level",
  "arrow, upper level",
  "arvel manor",
  "arvel manor, slave shack",
  "arvel manor, slavemaster's shack",
  "arvel manor, storage shack",
  "aryon ancestral tomb",
  "arys ancestral tomb",
  "asha-ahhe egg mine",
  "ashalmawia, shrine",
  "ashalmawia, shrine, sunken vaults",
  "ashalmimilkala, shrine",
  "ashamanu camp, kausha's yurt",
  "ashanammu",
  "ashimanu egg mine",
  "ashimanu egg mine, queen's lair",
  "ashinabi",
  "ashinabi, smuggler den",
  "ashir-dan",
  "ashirbadon",
  "ashmelech",
  "ashunartes, shrine",
  "ashurnibibi, shrine",
  "assalkushalit, shrine",
  "assarnatamat, shrine",
  "assarnud",
  "assemanu",
  "assemanu, shrine",
  "assernerairan, shrine",
  "assu",
  "assumanu",
  "assurdirapal, inner shrine",
  "assurdirapal, shrine",
  "assurnabitashpi",
  "assurnabitashpi, shrine",
  "bal fell, east wing",
  "bal fell, inner shrine",
  "bal fell, outer shrine",
  "bal fell, west wing",
  "bal ur, shrine",
  "bal ur, underground",
  "balmora, astius hanotepelus' house",
  "balmora, balyn omarel's house",
  "balmora, caius cosades' house",
  "balmora, clagius clanler: outfitter",
  "balmora, council club",
  "balmora, dorisa darvel: bookseller",
  "balmora, dralasa nithryon: pawnbroker",
  "balmora, dralcea arethi's house",
  "balmora, dralosa athren's house",
  "balmora, drarayne thelas' house",
  "balmora, drarayne thelas' storage",
  "balmora, dura gra-bol's house",
  "balmora, eastern guard tower",
  "balmora, eight plates",
  "balmora, fast eddie's house",
  "balmora, guild of fighters",
  "balmora, guild of mages",
  "balmora, hecerinde's house",
  "balmora, hlaalo manor",
  "balmora, hlaalu council manor",
  "balmora, itan's house",
  "balmora, karlirah's house",
  "balmora, lucky lockup",
  "balmora, meldor: armorer",
  "balmora, milie hastien: fine clothier",
  "balmora, morag tong guild",
  "balmora, nalcarya of white haven: fine alchemist",
  "balmora, nerano manor",
  "balmora, nine toes' house",
  "balmora, ra'virr: trader",
  "balmora, rarayn radarys' house",
  "balmora, rithleen's house",
  "balmora, south wall cornerclub",
  "balmora, temple",
  "balmora, the razor hole",
  "balmora, tsiya's house",
  "balmora, tyermaillin's house",
  "balmora, tyravel manor",
  "balmora, vorar helas' house",
  "balmora, vori's house",
  "balmora, western guard tower north",
  "balmora, western guard tower south",
  "balur's farmhouse",
  "bamz-amschend, hall of wails",
  "bamz-amschend, hall of winds",
  "bamz-amschend, hearthfire hall",
  "bamz-amschend, king's walk",
  "bamz-amschend, passage of the walker",
  "bamz-amschend, passage of whispers",
  "bamz-amschend, radac's forge",
  "bamz-amschend, skybreak gallery",
  "band egg mine",
  "baram ancestral tomb",
  "bensamsi",
  "bensiberib camp, odaishah's yurt",
  "beran ancestral tomb",
  "berandas, keep, bottom level",
  "berandas, keep, top level",
  "berandas, propylon chamber",
  "berandas, underground",
  "beshara",
  "big head's shack",
  "bthanchend",
  "bthuand",
  "bthungthumz",
  "buckmoth legion fort, interior",
  "buckmoth legion fort, prison",
  "buckmoth legion fort, towers",
  "caldera mine",
  "caldera, bashuk gra-bat's house",
  "caldera, canodia felannus' house",
  "caldera, dro'shavir's house",
  "caldera, elmussa damori's house",
  "caldera, falanaamo: clothier",
  "caldera, ghorak manor",
  "caldera, governor's hall",
  "caldera, guild of mages",
  "caldera, hodlismod: armorer",
  "caldera, irgola: pawnbroker",
  "caldera, keel-raniur's house",
  "caldera, mining bunkhouse",
  "caldera, mining company office",
  "caldera, mining guard tower",
  "caldera, nedhelas' house",
  "caldera, north guard towers",
  "caldera, odairan ashummi-ammus' house",
  "caldera, shenk's shovel",
  "caldera, slave shack one",
  "caldera, slave shack two",
  "caldera, south guard towers",
  "caldera, surane leoriane's house",
  "caldera, valvius mevureius' house",
  "caldera, verick gemain: trader",
  "cavern of the incarnate",
  "character stuff wonderland",
  "chun-ook, cabin",
  "chun-ook, lower level",
  "chun-ook, upper level",
  "clutter warehouse - everything must go!",
  "corprusarium",
  "corprusarium bowels",
  "dagon fel, andre maul's tower",
  "dagon fel, anja swift-sailer's house",
  "dagon fel, end of the world renter rooms",
  "dagon fel, fanar fork-beard's house",
  "dagon fel, fjorrod's house",
  "dagon fel, greidil half-troll's house",
  "dagon fel, heifnir: trader",
  "dagon fel, hurg's house",
  "dagon fel, itar the gentle's house",
  "dagon fel, mette's house",
  "dagon fel, onmi hard-mouth's house",
  "dagon fel, sorkvild's tower",
  "dagon fel, the end of the world",
  "dagon fel, vacant tower",
  "dagon fel, watch tower",
  "dagoth ur, facility cavern",
  "dagoth ur, inner facility",
  "dagoth ur, inner tower",
  "dagoth ur, lower facility",
  "dagoth ur, outer facility",
  "dareleth ancestral tomb",
  "derelict shipwreck, cabin",
  "derelict shipwreck, lower level",
  "derelict shipwreck, upper level",
  "deserted shipwreck, cabin",
  "deserted shipwreck, lower level",
  "deserted shipwreck, upper level",
  "desolate shipwreck, cabin",
  "desolate shipwreck, lower level",
  "desolate shipwreck, upper level",
  "dirara's farmhouse",
  "dissapla mine",
  "dralas ancestral tomb",
  "drath ancestral tomb",
  "draugr test",
  "dreloth ancestral tomb",
  "dren plantation, doves' shack",
  "dren plantation, dren's villa",
  "dren plantation, guardhouse",
  "dren plantation, helvi's shack",
  "dren plantation, hlevala's shack",
  "dren plantation, rethan's shack",
  "dren plantation, shipping house",
  "dren plantation, storage shack",
  "dren plantation, tower shack",
  "dren plantation, verethi and dralor",
  "drethan ancestral tomb",
  "drinith ancestral tomb",
  "drulene falen's hut",
  "druscashti, lower level",
  "druscashti, upper level",
  "dubdilla",
  "dubdilla, uncharted caverns",
  "dubdilla, uncharted caverns, lower",
  "dulo ancestral tomb",
  "dun-ahhe",
  "dunirai caverns",
  "dushariran, shrine",
  "ebernanit, shrine",
  "ebonheart, argonian mission",
  "ebonheart, east empire company hall",
  "ebonheart, east empire north warehouse",
  "ebonheart, east empire south warehouse",
  "ebonheart, grand council chambers",
  "ebonheart, grand council chambers tower",
  "ebonheart, hawkmoth legion garrison",
  "ebonheart, hawkmoth towers",
  "ebonheart, imperial chapels",
  "ebonheart, imperial commission",
  "ebonheart, imperial guard garrison",
  "ebonheart, six fishes",
  "ebonheart, skyrim mission",
  "ebonheart, underground caves",
  "elanius camp, yapal's yurt",
  "elf-skerring, cabin",
  "elf-skerring, lower level",
  "elf-skerring, upper level",
  "elith-pal mine",
  "eluba-addon egg mine",
  "eluba-addon grotto",
  "endusal, kagrenac's study",
  "erabenimsun camp, addut-lamanu's yurt",
  "erabenimsun camp, ainab's yurt",
  "erabenimsun camp, ashkhan's yurt",
  "erabenimsun camp, ashu-ahhe's yurt",
  "erabenimsun camp, assemmus' yurt",
  "erabenimsun camp, han-ammu's yurt",
  "erabenimsun camp, massarapal's yurt",
  "erabenimsun camp, ranabi's yurt",
  "erabenimsun camp, salattanat's yurt",
  "erabenimsun camp, wise woman's yurt",
  "eretammus-sennammu egg mine",
  "esutanamus, shrine",
  "fadathram ancestral tomb",
  "fair helas, cabin",
  "fair helas, lower level",
  "fair helas, upper level",
  "falas ancestral tomb",
  "falasmaryon, lower level",
  "falasmaryon, missun akin's hut",
  "falasmaryon, propylon chamber",
  "falasmaryon, sewers",
  "falasmaryon, upper level",
  "falensarano, lower level",
  "falensarano, propylon chamber",
  "falensarano, upper level",
  "falvillo's endeavor, cabin",
  "falvillo's endeavor, lower level",
  "falvilo's endeavor, upper level",
  "favel ancestral tomb",
  "forgotten shipwreck",
  "forgotten vaults of anudnabia, forge of hilbongard",
  "fort frostmoth, armory",
  "fort frostmoth, carius' chambers",
  "fort frostmoth, curtain wall",
  "fort frostmoth, general quarters",
  "fort frostmoth, general quarters, upper level",
  "fort frostmoth, imperial cult shrine",
  "fort frostmoth, prison",
  "fort frostmoth, supply room",
  "galom daeus, entry",
  "galom daeus, observatory",
  "ghostgate, temple",
  "ghostgate, tower of dawn",
  "ghostgate, tower of dawn lower level",
  "ghostgate, tower of dusk",
  "ghostgate, tower of dusk lower level",
  "gimothran ancestral tomb",
  "ginith ancestral tomb",
  "gnaar mok, anglalos's shack",
  "gnaar mok, arenim manor",
  "gnaar mok, caryarel's shack",
  "gnaar mok, druegh-jigger's rest",
  "gnaar mok, jerian dolbanitte's shack",
  "gnaar mok, mush-mere's shack",
  "gnaar mok, nadene rotheran's shack",
  "gnaar mok, rostlogi's shack",
  "gnisis, abelmawia hut",
  "gnisis, almu cave dwelling",
  "gnisis, arvs-drelen",
  "gnisis, barracks",
  "gnisis, bethamez",
  "gnisis, dinadad hut",
  "gnisis, eggmine",
  "gnisis, fort darius",
  "gnisis, lasamsi cave dwelling",
  "gnisis, lower eggmine",
  "gnisis, madach tradehouse",
  "gnisis, man-llu hut",
  "gnisis, mantiti cave dwelling",
  "gnisis, shand hut",
  "gnisis, shishara hut",
  "gnisis, tansumiran cave dwelling",
  "gnisis, temple",
  "gnisis, underground stream",
  "gnisis, vabdas hut",
  "gnisis, yahaz hut",
  "gro-bagrat plantation",
  "grytewake, cabin",
  "grytewake, lower level",
  "grytewake, upper level",
  "habinbaes",
  "hairat-vassamsi egg mine",
  "hairat-vassamsi egg mine, queen's lair",
  "halit mine",
  "hanud",
  "hanud, tower",
  "hassour",
  "hassour, shrine",
  "hawia egg mine",
  "helan ancestral tomb",
  "helas ancestral tomb",
  "heleran ancestral tomb",
  "heran ancestral tomb",
  "hinnabi",
  "hla oad, fadila balvel's house",
  "hla oad, fatleg's drop off",
  "hla oad, murudius flaeus's house",
  "hla oad, okur's house",
  "hla oad, relien rirne's house",
  "hla oad, shurkul gro-sharga's house",
  "hlaalu ancestral tomb",
  "hleran ancestral tomb",
  "hlervi ancestral tomb",
  "hlervu ancestral tomb",
  "hlormaren, dome",
  "hlormaren, keep, bottom level",
  "hlormaren, keep, top level",
  "hlormaren, propylon chamber",
  "hlormaren, sewers",
  "hlormaren, underground",
  "holamayan monastery",
  "ibar-dad",
  "ibishammus, shrine",
  "ienith ancestral tomb",
  "ihinipalit, shrine",
  "ilanipu grotto",
  "ilunibi, blackened heart",
  "ilunibi, carcass of the saint",
  "ilunibi, marowak's spine",
  "ilunibi, soul's rattle",
  "ilunibi, tainted marrow",
  "imperial prison ship",
  "inanius egg mine",
  "indalen ancestral tomb",
  "indaren ancestral tomb",
  "indarys manor",
  "indarys manor, berendas' house",
  "indarys manor, manor services",
  "indarys manor, raram's house",
  "indoranyon",
  "indoranyon, propylon chamber",
  "kaushtababi camp, adibael's yurt",
  "kaushtarari, shrine",
  "ken's test hole",
  "khuul, aldi's shack",
  "khuul, brurid's shack",
  "khuul, endris dilmyn's shack",
  "khuul, helga's shack",
  "khuul, miron garer's shack",
  "khuul, nelmyne andules's shack",
  "khuul, rivame samandas's shack",
  "khuul, svadstar's shack",
  "khuul, thongar's tradehouse",
  "koal cave",
  "kogoruhn, bleeding heart",
  "kogoruhn, charma's breath",
  "kogoruhn, dome of pollock's eve",
  "kogoruhn, dome of urso",
  "kogoruhn, hall of maki",
  "kogoruhn, hall of phisto",
  "kogoruhn, hall of the watchful touch",
  "kogoruhn, nabith waterway",
  "kogoruhn, temple of fey",
  "kogoruhn, vault of aerode",
  "kora-dur",
  "kudanat",
  "kumarahaz",
  "kunirai",
  "kushtashpi, shrine",
  "llando ancestral tomb",
  "lleran ancestral tomb",
  "llervu ancestral tomb",
  "llirala's shack",
  "llovyn's farmhouse",
  "lonely shipwreck, cabin",
  "lonely shipwreck, lower level",
  "lonely shipwreck, upper level",
  "lonesome shipwreck, cabin",
  "lonesome shipwreck, lower level",
  "lonesome shipwreck, upper level",
  "lost shipwreck, cabin",
  "lost shipwreck, lower level",
  "lost shipwreck, upper level",
  "maar gan, andus tradehouse",
  "maar gan, assi serimilk's hut",
  "maar gan, assirari zama-rasour's hut",
  "maar gan, garry's hut",
  "maar gan, guard tower 1",
  "maar gan, guard tower 2",
  "maar gan, guard tower 3",
  "maar gan, huleen's hut",
  "maar gan, kind erushara's hut",
  "maar gan, mabrelle geles's hut",
  "maar gan, outpost",
  "maar gan, shilipuran zama-rasour's hut",
  "maar gan, shrine",
  "maar gan, tashpi ashibael's hut",
  "maar gan, ulisamsi shaddarnuran's hut",
  "maar gan, yeherradad's hut",
  "maba-ilu",
  "mababi",
  "madas grotto",
  "madas-zebba egg mine",
  "maelkashishi, shrine",
  "maelkashishi, shrine, forgotten galleries",
  "maelu egg mine",
  "maesa-shammus egg mine",
  "magas volar",
  "mallapi",
  "malmus grotto",
  "mamaea, sanctum of awakening",
  "mamaea, sanctum of black hope",
  "mamaea, shrine of pitted dreams",
  "mamshar-disamus camp, maesat's yurt",
  "manat's farmhouse",
  "mannammu",
  "maran-adon",
  "marandus, dome",
  "marandus, lower level",
  "marandus, propylon chamber",
  "marandus, upper level",
  "maren ancestral tomb",
  "mark's script testing cell",
  "mark's vampire test cell",
  "marvani ancestral tomb",
  "massahanud camp, sargon's yurt",
  "massama cave",
  "masseranit",
  "mat",
  "matus-akin egg mine",
  "matus-akin egg mine, queen's lair",
  "mausur caverns",
  "mawia",
  "mila-nipal, manat's yurt",
  "milk",
  "minabi",
  "minabi, bandit lair",
  "ministry of truth, hall of processing",
  "ministry of truth, holding cells",
  "ministry of truth, prison keep",
  "missamsi",
  "missir-dadalit egg mine",
  "molag mar, armigers stronghold",
  "molag mar, canalworks",
  "molag mar, redoran stronghold",
  "molag mar, saetring the nord: smith",
  "molag mar, st. veloth's hostel",
  "molag mar, temple",
  "molag mar, the pilgrim's rest",
  "molag mar, underworks",
  "molag mar, vasesius viciulus: trader",
  "molag mar, waistworks",
  "moonmoth legion fort, interior",
  "moonmoth legion fort, prison towers",
  "morvayn manor",
  "mount kand, cavern",
  "mournhold",
  "mournhold temple",
  "mournhold temple: basement",
  "mournhold temple: hall of ministry",
  "mournhold temple: high chapel",
  "mournhold temple: infirmary",
  "mournhold temple: office of the lord archcanon",
  "mournhold temple: reception area",
  "mournhold, andoren manor",
  "mournhold, armory",
  "mournhold, bookseller",
  "mournhold, clothier",
  "mournhold, craftsmen's hall",
  "mournhold, geon auline's house",
  "mournhold, godsreach",
  "mournhold, great bazaar",
  "mournhold, ignatius flaccus' house",
  "mournhold, llethan manor",
  "mournhold, magic shop",
  "mournhold, museum of artifacts",
  "mournhold, pawnbroker",
  "mournhold, plaza brindisi dorom",
  "mournhold, royal palace",
  "mournhold, royal palace throne room",
  "mournhold, royal palace: barenziah's chambers",
  "mournhold, royal palace: basement",
  "mournhold, royal palace: courtyard",
  "mournhold, royal palace: guards' quarters",
  "mournhold, royal palace: helseth's chambers",
  "mournhold, royal palace: imperial cult services",
  "mournhold, royal palace: jail",
  "mournhold, royal palace: legion depot",
  "mournhold, royal palace: reception area",
  "mournhold, sadri manor",
  "mournhold, secret office",
  "mournhold, temple courtyard",
  "mournhold, the winged guar",
  "mournhold, thendas manor",
  "mournhold, trader",
  "mournhold, vacant manor",
  "mournhold, velas manor",
  "mudan grotto",
  "mudan-mul egg mine",
  "mudan, central vault",
  "mudan, lost dwemer checkpoint",
  "mudan, right tower",
  "mul grotto",
  "mzahnch",
  "mzahnch lower level",
  "mzanchend",
  "mzuleft",
  "nallit",
  "nammu",
  "nchardahrk",
  "nchardumz",
  "nchardumz lower level",
  "nchuleft",
  "nchuleftingth, lower levels",
  "nchuleftingth, test of pattern",
  "nchuleftingth, upper levels",
  "nchurdamz, interior",
  "neglected shipwreck, cabin",
  "neglected shipwreck, lower level",
  "neglected shipwreck, upper level",
  "nelas ancestral tomb",
  "nerano ancestral tomb",
  "nilera's farmhouse",
  "nimawia grotto",
  "nissintu",
  "norenen-dur",
  "norenen-dur, basilica of divine whispers",
  "norenen-dur, citadel of myn dhrur",
  "norenen-dur, the grand stair",
  "norenen-dur, the teeth that gnash",
  "norenen-dur, the wailingdelve",
  "norvayn ancestral tomb",
  "nund",
  "obscure shipwreck, cabin",
  "obscure shipwreck, lower level",
  "obscure shipwreck, upper level",
  "odaishah",
  "odibaal",
  "odirnamat",
  "odirniran",
  "odirniran, tower",
  "odrosal, dwemer training academy",
  "odrosal, tower",
  "old mournhold: abandoned crypt",
  "old mournhold: abandoned passageway",
  "old mournhold: armory ruins",
  "old mournhold: battlefield",
  "old mournhold: bazaar sewers",
  "old mournhold: city gate",
  "old mournhold: forgotten sewer",
  "old mournhold: gedna relvel's tomb",
  "old mournhold: manor district",
  "old mournhold: moril manor, courtyard",
  "old mournhold: moril manor, east building",
  "old mournhold: moril manor, north building",
  "old mournhold: palace sewers",
  "old mournhold: residential ruins",
  "old mournhold: residential sewers",
  "old mournhold: tears of amun-shae",
  "old mournhold: temple catacombs",
  "old mournhold: temple crypt",
  "old mournhold: temple gardens",
  "old mournhold: temple sewers",
  "old mournhold: temple sewers east",
  "old mournhold: temple sewers west",
  "old mournhold: temple shrine",
  "old mournhold: teran hall",
  "old mournhold: teran hall, east bldg",
  "old mournhold: west sewers",
  "omalen ancestral tomb",
  "omani manor",
  "omaren ancestral tomb",
  "onnissiralis, shrine",
  "orethi ancestral tomb",
  "othrelas ancestral tomb",
  "palansour",
  "panabanit-nimawia egg mine",
  "panat",
  "panud egg mine",
  "pelagiad, adanja's house",
  "pelagiad, ahnassi's house",
  "pelagiad, dralas gilu's house",
  "pelagiad, erval's house",
  "pelagiad, farusea salas' house",
  "pelagiad, fort pelagiad",
  "pelagiad, guard tower",
  "pelagiad, halfway tavern",
  "pelagiad, ignatius flaccus' house",
  "pelagiad, junal-lei's house",
  "pelagiad, madres navur's house",
  "pelagiad, mebestien ence: trader",
  "pelagiad, murberius harmevus' house",
  "pelagiad, north wall",
  "pelagiad, south wall",
  "pelagiad, uulernil : armorer",
  "piernette's farmhouse",
  "pinsun",
  "piran",
  "prelude shipwreck, cabin",
  "prelude shipwreck, lower level",
  "prelude shipwreck, upper level",
  "pudai egg mine",
  "pudai egg mine, queen's lair",
  "pulk",
  "punabi",
  "punammu",
  "punsabanit",
  "ramimilk, shrine",
  "randas ancestral tomb",
  "ravel ancestral tomb",
  "raven rock, abandoned mine shaft",
  "raven rock, afer flaccus' house",
  "raven rock, bar",
  "raven rock, factor's estate",
  "raven rock, garnas uvalen's house",
  "raven rock, gidar verothan's house",
  "raven rock, gratian caerellius' house",
  "raven rock, mine",
  "raven rock, mine entrance",
  "raven rock, north storehouse",
  "raven rock, sabinus oranius' house",
  "raven rock, sados relothan's house",
  "raven rock, seler favelnim's house",
  "raven rock, smith",
  "raven rock, south storehouse",
  "raven rock, southeast storehouse",
  "raven rock, supply ship",
  "raven rock, trader",
  "raven rock, uryn maren's house",
  "raven rock, vacant house",
  "raviro ancestral tomb",
  "rayna drolan's shack",
  "redas ancestral tomb",
  "redoran interior",
  "redoran interior2",
  "releth ancestral tomb",
  "reloth ancestral tomb",
  "remote shipwreck, cabin",
  "remote shipwreck, lower level",
  "remote shipwreck, upper level",
  "rethan manor",
  "rethan manor, berendas' house",
  "rethan manor, drelas' house",
  "rethan manor, gols' house",
  "rethan manor, tures' house",
  "rethandus ancestral tomb",
  "rissun",
  "rothan ancestral tomb",
  "rotheran, arena",
  "rotheran, communal hut",
  "rotheran, propylon chamber",
  "sadrith mora, anis seloth: alchemist",
  "sadrith mora, balen vendu: monk",
  "sadrith mora, dirty muriel's cornerclub",
  "sadrith mora, fara's hole in the wall",
  "sadrith mora, gateway inn",
  "sadrith mora, gateway inn: north wing",
  "sadrith mora, gateway inn: south wing",
  "sadrith mora, gateway inn: west wing",
  "sadrith mora, hleras gidren's house",
  "sadrith mora, llaalam madalas: mage",
  "sadrith mora, madran ulvel's house",
  "sadrith mora, meluria seleth's house",
  "sadrith mora, milara vedran's house",
  "sadrith mora, morag tong guild",
  "sadrith mora, nevrila areloth's house",
  "sadrith mora, nirasa aren's house",
  "sadrith mora, pierlette rostorard: apothecary",
  "sadrith mora, rolis garvon's house",
  "sadrith mora, tel naga general quarters",
  "sadrith mora, tel naga great hall",
  "sadrith mora, tel naga upper hall",
  "sadrith mora, tel naga upper tower",
  "sadrith mora, telvanni council house",
  "sadrith mora, telvanni council house, chambers",
  "sadrith mora, telvanni council house, entry",
  "sadrith mora, telvanni council house, hermitage",
  "sadrith mora, thervul serethi: healer",
  "sadrith mora, trendrus dral's house",
  "sadrith mora, urtisa romayn's house",
  "sadrith mora, urtiso faryon: sorcerer",
  "sadrith mora, vaden belas' house",
  "sadrith mora, volmyni dral's house",
  "sadrith mora, wolverine hall",
  "sadrith mora, wolverine hall: fighter's guild",
  "sadrith mora, wolverine hall: imperial shrine",
  "sadrith mora, wolverine hall: mage's guild",
  "sadryon ancestral tomb",
  "salit camp, zalit's yurt",
  "salit camp, zelay's yurt",
  "salmantu",
  "salmantu, shrine",
  "salothan ancestral tomb",
  "salothran ancestral tomb",
  "salvel ancestral tomb",
  "samarys ancestral tomb",
  "sanabi",
  "sandas ancestral tomb",
  "sandus ancestral tomb",
  "sanit",
  "sanit, shrine",
  "sanni",
  "sarano ancestral tomb",
  "saren ancestral tomb",
  "sarethi ancestral tomb",
  "sargon",
  "sarimisun-assa egg mine",
  "sarimisun-assa egg mine, queen's lair",
  "sarys ancestral tomb",
  "saturan",
  "savel ancestral tomb",
  "senim ancestral tomb",
  "sennananit",
  "seran ancestral tomb",
  "serano ancestral tomb",
  "sethan ancestral tomb",
  "setus egg mine",
  "seyda neen, arrille's tradehouse",
  "seyda neen, census and excise office",
  "seyda neen, census and excise warehouse",
  "seyda neen, draren thiralas' house",
  "seyda neen, eldafire's house",
  "seyda neen, erene llenim's shack",
  "seyda neen, fargoth's house",
  "seyda neen, fine-mouth's shack",
  "seyda neen, foryn gilnith's shack",
  "seyda neen, indrele rathryon's shack",
  "seyda neen, lighthouse",
  "seyda neen, terurise girvayne's house",
  "seyda neen, vodunius nuccius' house",
  "sha-adnius",
  "shal",
  "shallit",
  "shara",
  "sharapli",
  "shashmanu camp, anit's yurt",
  "shashpilamat",
  "shashpilamat, shrine",
  "shashurari camp, zennammu's yurt",
  "shishara",
  "shishi",
  "shrine of azura",
  "shulk egg mine",
  "shulk egg mine, mining camp",
  "shulk egg mine, queen's lair",
  "shunned shipwreck, cabin",
  "shunned shipwreck, lower level",
  "shunned shipwreck, upper level",
  "shurdan-raplay egg mine",
  "shurinbaal",
  "shushan",
  "shushishi",
  "sinamusa egg mine",
  "sinarralit egg mine",
  "sinsibadon",
  "sjorvar horse-mouth's house",
  "skaal village, bronrod the roarer's house",
  "skaal village, erna the quiet's house",
  "skaal village, ice-mane's hut",
  "skaal village, ingmar's house",
  "skaal village, lassnr's house",
  "skaal village, rigmor's hut",
  "skaal village, shaman's hut",
  "skaal village, snedbrir the smith",
  "skaal village, the blodskaal's house",
  "skaal village, the greathall",
  "small farmhouse",
  "sobitbael camp, mal's yurt",
  "solstheim",
  "solstheim, aesliip's lair",
  "solstheim, aesliip's lair, caverns",
  "solstheim, benkongerike",
  "solstheim, bjorn",
  "solstheim, bloodskal barrow",
  "solstheim, castle karstaag, banquet hall",
  "solstheim, castle karstaag, caverns of karstaag",
  "solstheim, castle karstaag, karstaag's chambers",
  "solstheim, castle karstaag, throne room",
  "solstheim, castle karstaag, tower",
  "solstheim, cave of hidden music",
  "solstheim, caves of fjalding",
  "solstheim, chamber of song",
  "solstheim, connorflenge barrow",
  "solstheim, domme",
  "solstheim, eddard barrow",
  "solstheim, fjell",
  "solstheim, frossel",
  "solstheim, frosselmane barrow",
  "solstheim, frykte",
  "solstheim, gandrung caverns",
  "solstheim, geilir the mumbling's dwelling",
  "solstheim, glenschul's tomb",
  "solstheim, gloomy cave",
  "solstheim, graring's house",
  "solstheim, gronn",
  "solstheim, gyldenhul barrow",
  "solstheim, halls of penumbra",
  "solstheim, himmelhost barrow",
  "solstheim, hrothmund's barrow",
  "solstheim, jolgeirr barrow",
  "solstheim, kelsedolk barrow",
  "solstheim, kjolver's dwelling",
  "solstheim, kolbjorn barrow",
  "solstheim, kolfinna's dwelling",
  "solstheim, lair of the udyrfrykte",
  "solstheim, legge",
  "solstheim, lukesturm barrow",
  "solstheim, mortrag glacier: entry",
  "solstheim, mortrag glacier: huntsman's hall",
  "solstheim, mortrag glacier: inner ring",
  "solstheim, mortrag glacier: outer ring",
  "solstheim, rimhull",
  "solstheim, sjobal",
  "solstheim, skogsdrake barrow",
  "solstheim, skygge",
  "solstheim, solvjord",
  "solstheim, stahlman's gorge",
  "solstheim, stormpfund barrow",
  "solstheim, thirsk",
  "solstheim, tombs of skaalara",
  "solstheim, ulfgar the unending's dwelling",
  "solstheim, uncle sweetshare's workshop",
  "solstheim, valbrandr barrow",
  "solstheim, varstaad caves",
  "sotha sil,",
  "sotha sil, central gearworks",
  "sotha sil, chamber of sohleh",
  "sotha sil, dome of kasia",
  "sotha sil, dome of serlyn",
  "sotha sil, dome of sotha sil",
  "sotha sil, dome of the imperfect",
  "sotha sil, dome of udok",
  "sotha sil, hall of delirium",
  "sotha sil, hall of mileitho",
  "sotha sil, hall of sallaemu",
  "sotha sil, hall of theuda",
  "sotha sil, inner flooded halls",
  "sotha sil, outer flooded halls",
  "sterdecan's farmhouse",
  "strange shipwreck, cabin",
  "strange shipwreck, lower level",
  "strange shipwreck, upper level",
  "subdun",
  "subdun, shrine",
  "sud",
  "sudanit mine",
  "sulipund",
  "sur egg mine",
  "suran, desele's house of earthly delights",
  "suran, garothmuk gro-muzgub: smith",
  "suran, goldyn belaram: pawnbroker",
  "suran, guard tower",
  "suran, ibarnadad assirnarari: apothecary",
  "suran, oran manor",
  "suran, ralds oril: trader",
  "suran, ranosa gilvayn: outfitter",
  "suran, suran slave market",
  "suran, suran temple",
  "suran, suran tradehouse",
  "suran, verara rendo: clothier",
  "surirulk",
  "tel aruhn, aryne telnim: smith",
  "tel aruhn, bildren areleth: apothecary",
  "tel aruhn, ferele athram: trader",
  "tel aruhn, maren uvaren: enchanter",
  "tel aruhn, plot and plaster",
  "tel aruhn, tower entry",
  "tel aruhn, tower living quarters",
  "tel aruhn, underground",
  "tel aruhn, upper tower",
  "tel branora, ervyna hlervu's shack",
  "tel branora, evos goran's house",
  "tel branora, fadase selvayn: trader",
  "tel branora, fedar davus's house",
  "tel branora, galen berer: armorer",
  "tel branora, giron manas's shack",
  "tel branora, lower tower",
  "tel branora, manos vavyn's house",
  "tel branora, seryne relas's house",
  "tel branora, sethan's tradehouse",
  "tel branora, tower dungeon",
  "tel branora, tower guardpost",
  "tel branora, upper tower",
  "tel branora, upper tower: therana's chamber",
  "tel mora, berwen: trader",
  "tel mora, elegnan: clothier",
  "tel mora, jolda: apothecary",
  "tel mora, kirsty's house",
  "tel mora, liette's house",
  "tel mora, lower tower",
  "tel mora, nona's house",
  "tel mora, radras: smith",
  "tel mora, the covenant",
  "tel mora, tower services",
  "tel mora, upper tower",
  "tel uvirith, arelas' house",
  "tel uvirith, menas' house",
  "tel uvirith, omavel's house",
  "tel uvirith, seleth's house",
  "tel uvirith, tower dungeon",
  "tel uvirith, tower lower",
  "tel uvirith, tower upper",
  "tel vos, aryon's chambers",
  "tel vos, barracks and armory",
  "tel vos, central tower",
  "tel vos, dungeon",
  "tel vos, jail",
  "tel vos, northeastern tower",
  "tel vos, services tower",
  "tel vos, southern tower",
  "telasero, lower level",
  "telasero, propylon chamber",
  "telasero, upper level",
  "telvayn ancestral tomb",
  "thalas ancestral tomb",
  "tharys ancestral tomb",
  "thelas ancestral tomb",
  "thiralas ancestral tomb",
  "tin-ahhe",
  "toddtest",
  "tower of tel fyr, hall of fyr",
  "tower of tel fyr, onyx hall",
  "tukushapal",
  "tukushapal, sepulcher",
  "tureynulal, bladder of clovis",
  "tureynulal, eye of duggan",
  "tureynulal, eye of thom wye",
  "tureynulal, kagrenac's library",
  "tusenend, shrine",
  "ularradallaku, shrine",
  "ules manor",
  "ules manor, slave shack",
  "ules manor, slavemaster's shack",
  "ulummusa",
  "uncharted shipwreck, lower level",
  "unchartered shipwreck, cabin",
  "unchartered shipwreck, upper level",
  "unexplored shipwreck, cabin",
  "unexplored shipwreck, lower level",
  "unexplored shipwreck, upper level",
  "unknown shipwreck, cabin",
  "unknown shipwreck, lower level",
  "unknown shipwreck, upper level",
  "unmarked shipwreck, lower level",
  "unmarked shipwreck, upper level",
  "urshilaku camp, ahasour's yurt",
  "urshilaku camp, ashkhan's yurt",
  "urshilaku camp, kurapli's yurt",
  "urshilaku camp, maeli's yurt",
  "urshilaku camp, sakiran's yurt",
  "urshilaku camp, shara's yurt",
  "urshilaku camp, shimsun's yurt",
  "urshilaku camp, wise woman's yurt",
  "urshilaku camp, zabamund's yurt",
  "urshilaku camp, zanummu's yurt",
  "urshilaku, astral burial",
  "urshilaku, fragile burial",
  "urshilaku, juno burial",
  "urshilaku, kakuna burial",
  "urshilaku, karma burial",
  "urshilaku, kefka burial",
  "urshilaku, laterus burial",
  "uveran ancestral tomb",
  "valenvaryon, durz's hut",
  "valenvaryon, gashna's hut",
  "valenvaryon, lambug's hut",
  "valenvaryon, lurog's hut",
  "valenvaryon, propylon chamber",
  "valenvaryon, umug's hut",
  "vandus ancestral tomb",
  "vansunalit egg mine",
  "vas, entry level",
  "vas, tower",
  "vassamsi grotto",
  "vassir-didanat cave",
  "velas ancestral tomb",
  "veloth ancestral tomb",
  "vemynal, hall of torque",
  "vemynal, outer fortress",
  "venim ancestral tomb",
  "verelnim ancestral tomb",
  "vivec, agrippina herennia: clothier",
  "vivec, alusaron: smith",
  "vivec, andilu drothan: alchemist",
  "vivec, arena canalworks",
  "vivec, arena fighters quarters",
  "vivec, arena fighters training",
  "vivec, arena hidden area",
  "vivec, arena holding cells",
  "vivec, arena pit",
  "vivec, arena storage",
  "vivec, arena underworks",
  "vivec, arena waistworks",
  "vivec, aurane frernis: apothecary",
  "vivec, black shalk cornerclub",
  "vivec, canon offices",
  "vivec, canon quarters",
  "vivec, curio manor",
  "vivec, dralor manor",
  "vivec, elven nations cornerclub",
  "vivec, foreign quarter canalworks",
  "vivec, foreign quarter lower waistworks",
  "vivec, foreign quarter plaza",
  "vivec, foreign quarter tomb",
  "vivec, foreign quarter underworks",
  "vivec, foreign quarter upper waistworks",
  "vivec, guild of fighters",
  "vivec, guild of mages",
  "vivec, hall of justice",
  "vivec, hall of justice secret library",
  "vivec, hall of wisdom",
  "vivec, hall underworks",
  "vivec, high fane",
  "vivec, hlaalu alchemist",
  "vivec, hlaalu ancestral vaults",
  "vivec, hlaalu canalworks",
  "vivec, hlaalu edryno arethi's house",
  "vivec, hlaalu general goods",
  "vivec, hlaalu pawnbroker",
  "vivec, hlaalu plaza",
  "vivec, hlaalu prison cells",
  "vivec, hlaalu records",
  "vivec, hlaalu temple",
  "vivec, hlaalu treasury",
  "vivec, hlaalu underworks",
  "vivec, hlaalu vaults",
  "vivec, hlaalu waistworks",
  "vivec, hlaalu weaponsmith",
  "vivec, hlaren residence",
  "vivec, j'rasha: healer",
  "vivec, jeanne: trader",
  "vivec, jobasha's rare books",
  "vivec, justice offices",
  "vivec, library of vivec",
  "vivec, lucretinaus olcinius: trader",
  "vivec, mevel fererus: trader",
  "vivec, milo's quarters",
  "vivec, miun-gei: enchanter",
  "vivec, no name club",
  "vivec, office of the watch",
  "vivec, ordinator barracks",
  "vivec, palace of vivec",
  "vivec, puzzle canal, center",
  "vivec, puzzle canal, level 1",
  "vivec, puzzle canal, level 2",
  "vivec, puzzle canal, level 3",
  "vivec, puzzle canal, level 4",
  "vivec, puzzle canal, level 5",
  "vivec, ralen tilvur: smith",
  "vivec, redoran ancestral vaults",
  "vivec, redoran canalworks",
  "vivec, redoran plaza",
  "vivec, redoran prison cells",
  "vivec, redoran records",
  "vivec, redoran scout & drillmaster",
  "vivec, redoran smith",
  "vivec, redoran temple shrine",
  "vivec, redoran trader",
  "vivec, redoran treasury",
  "vivec, redoran underworks",
  "vivec, redoran vaults",
  "vivec, redoran waistworks",
  "vivec, saren manor",
  "vivec, simine fralinie: bookseller",
  "vivec, st. delyn canal north-one",
  "vivec, st. delyn canal north-three",
  "vivec, st. delyn canal north-two",
  "vivec, st. delyn canal south-one",
  "vivec, st. delyn canal south-three",
  "vivec, st. delyn canal south-two",
  "vivec, st. delyn canalworks",
  "vivec, st. delyn glassworker's hall",
  "vivec, st. delyn plaza",
  "vivec, st. delyn potter's hall",
  "vivec, st. delyn storage",
  "vivec, st. delyn underworks",
  "vivec, st. delyn waist north-one",
  "vivec, st. delyn waist north-two",
  "vivec, st. delyn waist south-one",
  "vivec, st. delyn waist south-two",
  "vivec, st. delyn waistworks",
  "vivec, st. olms brewers and fishmongers hall",
  "vivec, st. olms canal north-one",
  "vivec, st. olms canal north-three",
  "vivec, st. olms canal north-two",
  "vivec, st. olms canal south-one",
  "vivec, st. olms canal south-three",
  "vivec, st. olms canal south-two",
  "vivec, st. olms canalworks",
  "vivec, st. olms farmers and laborers hall",
  "vivec, st. olms haunted manor",
  "vivec, st. olms plaza",
  "vivec, st. olms storage",
  "vivec, st. olms tailors and dyers hall",
  "vivec, st. olms tanners and miners hall",
  "vivec, st. olms temple",
  "vivec, st. olms underworks",
  "vivec, st. olms upper north-one",
  "vivec, st. olms upper north-two",
  "vivec, st. olms upper south-one",
  "vivec, st. olms waist north-one",
  "vivec, st. olms waist north-two",
  "vivec, st. olms waist south-one",
  "vivec, st. olms waist south-two",
  "vivec, st. olms waistworks",
  "vivec, st. olms yngling manor",
  "vivec, st. olms yngling manor basement",
  "vivec, telvanni alchemist",
  "vivec, telvanni apothecary",
  "vivec, telvanni canalworks",
  "vivec, telvanni enchanter",
  "vivec, telvanni mage",
  "vivec, telvanni monster lab",
  "vivec, telvanni plaza",
  "vivec, telvanni prison cells",
  "vivec, telvanni sorcerer",
  "vivec, telvanni temple",
  "vivec, telvanni tower",
  "vivec, telvanni underworks",
  "vivec, telvanni upper storage",
  "vivec, telvanni vault",
  "vivec, telvanni waistworks",
  "vivec, temporary telvanni housing",
  "vivec, tervur braven: trader",
  "vivec, the abbey of st. delyn the wise",
  "vivec, the flowers of gold",
  "vivec, the lizard's head",
  "vor lair, chambers of alta vor",
  "vor lair, interior",
  "vos, dreynos elvul's farmhouse",
  "vos, fanisea irano's farmhouse",
  "vos, ienasa radas's farmhouse",
  "vos, maela kaushad's farmhouse",
  "vos, mandyn ralas's farmhouse",
  "vos, menus felas's farmhouse",
  "vos, runethyne andas's farmhouse",
  "vos, thilse aralas's farmhouse",
  "vos, trilam drolnor's farmhouse",
  "vos, ulvil llothas's farmhouse",
  "vos, varo tradehouse",
  "vos, varo tradehouse entrance",
  "vos, varo tradehouse storage",
  "vos, vos chapel",
  "yakanalit",
  "yakaridan camp, kitbael's yurt",
  "yakin",
  "yakin, shrine",
  "yanemus mine",
  "yansirramus, shrine",
  "yasammidan, shrine",
  "yasamsi",
  "yassu mine",
  "yesamsi",
  "zainab camp, ababael timsar-dadisun's yurt",
  "zainab camp, ashibaal's yurt",
  "zainab camp, ashkhan's yurt",
  "zainab camp, ashur-dan's yurt",
  "zainab camp, kuda's yurt",
  "zainab camp, kummu's yurt",
  "zainab camp, minassour's yurt",
  "zainab camp, patababi's yurt",
  "zainab camp, tussi's yurt",
  "zainab camp, wise woman's yurt",
  "zainsipilu",
  "zaintirari",
  "zaintiraris, shrine",
  "zalkin grotto",
  "zalkin-sul egg mine",
  "zanabi",
  "zebabi",
  "zenarbael",
  "zergonipal, shrine",
])

const officialExteriorCells = new Set([
  "-29,23",
  "-28,18",
  "-28,19",
  "-28,20",
  "-28,21",
  "-28,22",
  "-28,23",
  "-28,24",
  "-27,18",
  "-27,19",
  "-27,20",
  "-27,21",
  "-27,22",
  "-27,23",
  "-27,24",
  "-27,25",
  "-27,26",
  "-27,27",
  "-26,16",
  "-26,17",
  "-26,18",
  "-26,19",
  "-26,20",
  "-26,21",
  "-26,22",
  "-26,23",
  "-26,24",
  "-26,25",
  "-26,26",
  "-26,27",
  "-26,28",
  "-25,14",
  "-25,15",
  "-25,16",
  "-25,17",
  "-25,18",
  "-25,19",
  "-25,20",
  "-25,21",
  "-25,22",
  "-25,23",
  "-25,24",
  "-25,25",
  "-25,26",
  "-25,27",
  "-25,28",
  "-24,14",
  "-24,15",
  "-24,16",
  "-24,17",
  "-24,18",
  "-24,19",
  "-24,20",
  "-24,21",
  "-24,22",
  "-24,23",
  "-24,24",
  "-24,25",
  "-24,26",
  "-24,27",
  "-23,14",
  "-23,15",
  "-23,16",
  "-23,17",
  "-23,18",
  "-23,19",
  "-23,20",
  "-23,21",
  "-23,22",
  "-23,23",
  "-23,24",
  "-23,25",
  "-23,26",
  "-23,27",
  "-22,15",
  "-22,16",
  "-22,17",
  "-22,18",
  "-22,19",
  "-22,20",
  "-22,21",
  "-22,22",
  "-22,23",
  "-22,24",
  "-22,25",
  "-22,26",
  "-22,27",
  "-21,15",
  "-21,16",
  "-21,17",
  "-21,18",
  "-21,19",
  "-21,20",
  "-21,21",
  "-21,22",
  "-21,23",
  "-21,24",
  "-21,25",
  "-21,26",
  "-21,27",
  "-21,28",
  "-20,15",
  "-20,16",
  "-20,17",
  "-20,18",
  "-20,19",
  "-20,20",
  "-20,21",
  "-20,22",
  "-20,23",
  "-20,24",
  "-20,25",
  "-20,26",
  "-20,27",
  "-19,14",
  "-19,15",
  "-19,16",
  "-19,17",
  "-19,18",
  "-19,19",
  "-19,20",
  "-19,21",
  "-19,22",
  "-19,23",
  "-19,24",
  "-19,25",
  "-19,26",
  "-19,27",
  "-19,28",
  "-18,10",
  "-18,11",
  "-18,12",
  "-18,13",
  "-18,14",
  "-18,16",
  "-18,17",
  "-18,18",
  "-18,19",
  "-18,20",
  "-18,21",
  "-18,22",
  "-18,23",
  "-18,24",
  "-18,25",
  "-18,26",
  "-18,27",
  "-18,28",
  "-17,9",
  "-17,10",
  "-17,11",
  "-17,12",
  "-17,13",
  "-17,14",
  "-17,15",
  "-17,16",
  "-17,17",
  "-17,18",
  "-17,19",
  "-17,20",
  "-17,21",
  "-17,22",
  "-17,23",
  "-17,24",
  "-17,25",
  "-17,26",
  "-16,7",
  "-16,8",
  "-16,9",
  "-16,10",
  "-16,11",
  "-16,12",
  "-16,13",
  "-16,14",
  "-16,15",
  "-16,16",
  "-16,17",
  "-16,23",
  "-16,24",
  "-16,25",
  "-15,-8",
  "-15,7",
  "-15,8",
  "-15,9",
  "-15,10",
  "-15,11",
  "-15,12",
  "-15,13",
  "-15,14",
  "-15,15",
  "-15,16",
  "-15,17",
  "-14,2",
  "-14,4",
  "-14,5",
  "-14,6",
  "-14,7",
  "-14,8",
  "-14,9",
  "-14,10",
  "-14,11",
  "-14,12",
  "-14,13",
  "-14,14",
  "-14,15",
  "-14,16",
  "-14,17",
  "-13,1",
  "-13,2",
  "-13,3",
  "-13,4",
  "-13,5",
  "-13,6",
  "-13,7",
  "-13,8",
  "-13,9",
  "-13,10",
  "-13,11",
  "-13,12",
  "-13,13",
  "-13,14",
  "-13,15",
  "-13,16",
  "-13,17",
  "-13,18",
  "-12,1",
  "-12,2",
  "-12,3",
  "-12,4",
  "-12,5",
  "-12,6",
  "-12,7",
  "-12,8",
  "-12,9",
  "-12,10",
  "-12,11",
  "-12,12",
  "-12,13",
  "-12,14",
  "-12,15",
  "-12,16",
  "-12,17",
  "-12,18",
  "-12,19",
  "-12,20",
  "-11,-1",
  "-11,0",
  "-11,1",
  "-11,2",
  "-11,3",
  "-11,4",
  "-11,5",
  "-11,6",
  "-11,7",
  "-11,8",
  "-11,9",
  "-11,10",
  "-11,11",
  "-11,12",
  "-11,13",
  "-11,14",
  "-11,15",
  "-11,16",
  "-11,17",
  "-11,18",
  "-11,19",
  "-11,20",
  "-10,-9",
  "-10,-8",
  "-10,-7",
  "-10,-6",
  "-10,-5",
  "-10,-4",
  "-10,-3",
  "-10,-2",
  "-10,-1",
  "-10,0",
  "-10,1",
  "-10,2",
  "-10,3",
  "-10,4",
  "-10,5",
  "-10,6",
  "-10,7",
  "-10,8",
  "-10,9",
  "-10,10",
  "-10,11",
  "-10,12",
  "-10,13",
  "-10,14",
  "-10,15",
  "-10,16",
  "-10,17",
  "-10,18",
  "-10,19",
  "-10,20",
  "-9,-14",
  "-9,-13",
  "-9,-12",
  "-9,-11",
  "-9,-10",
  "-9,-9",
  "-9,-8",
  "-9,-7",
  "-9,-6",
  "-9,-5",
  "-9,-4",
  "-9,-3",
  "-9,-2",
  "-9,-1",
  "-9,0",
  "-9,1",
  "-9,2",
  "-9,3",
  "-9,4",
  "-9,5",
  "-9,6",
  "-9,7",
  "-9,8",
  "-9,9",
  "-9,10",
  "-9,11",
  "-9,12",
  "-9,13",
  "-9,14",
  "-9,15",
  "-9,16",
  "-9,17",
  "-9,18",
  "-9,19",
  "-9,20",
  "-8,-14",
  "-8,-13",
  "-8,-12",
  "-8,-11",
  "-8,-10",
  "-8,-9",
  "-8,-8",
  "-8,-7",
  "-8,-6",
  "-8,-5",
  "-8,-4",
  "-8,-3",
  "-8,-2",
  "-8,-1",
  "-8,0",
  "-8,1",
  "-8,2",
  "-8,3",
  "-8,4",
  "-8,5",
  "-8,6",
  "-8,7",
  "-8,8",
  "-8,9",
  "-8,10",
  "-8,11",
  "-8,12",
  "-8,13",
  "-8,14",
  "-8,15",
  "-8,16",
  "-8,17",
  "-8,18",
  "-8,19",
  "-8,20",
  "-8,21",
  "-8,22",
  "-7,-14",
  "-7,-13",
  "-7,-12",
  "-7,-11",
  "-7,-10",
  "-7,-9",
  "-7,-8",
  "-7,-7",
  "-7,-6",
  "-7,-5",
  "-7,-4",
  "-7,-3",
  "-7,-2",
  "-7,-1",
  "-7,0",
  "-7,1",
  "-7,2",
  "-7,3",
  "-7,4",
  "-7,5",
  "-7,6",
  "-7,7",
  "-7,8",
  "-7,9",
  "-7,10",
  "-7,11",
  "-7,12",
  "-7,13",
  "-7,14",
  "-7,15",
  "-7,16",
  "-7,17",
  "-7,18",
  "-7,19",
  "-7,20",
  "-7,21",
  "-7,22",
  "-7,23",
  "-7,24",
  "-6,-14",
  "-6,-13",
  "-6,-12",
  "-6,-11",
  "-6,-10",
  "-6,-9",
  "-6,-8",
  "-6,-7",
  "-6,-6",
  "-6,-5",
  "-6,-4",
  "-6,-3",
  "-6,-2",
  "-6,-1",
  "-6,0",
  "-6,1",
  "-6,2",
  "-6,3",
  "-6,4",
  "-6,5",
  "-6,6",
  "-6,7",
  "-6,8",
  "-6,9",
  "-6,10",
  "-6,11",
  "-6,12",
  "-6,13",
  "-6,14",
  "-6,15",
  "-6,16",
  "-6,17",
  "-6,18",
  "-6,19",
  "-6,20",
  "-6,21",
  "-6,22",
  "-6,23",
  "-6,24",
  "-6,25",
  "-5,-14",
  "-5,-13",
  "-5,-12",
  "-5,-11",
  "-5,-10",
  "-5,-9",
  "-5,-8",
  "-5,-7",
  "-5,-6",
  "-5,-5",
  "-5,-4",
  "-5,-3",
  "-5,-2",
  "-5,-1",
  "-5,0",
  "-5,1",
  "-5,2",
  "-5,3",
  "-5,4",
  "-5,5",
  "-5,6",
  "-5,7",
  "-5,8",
  "-5,9",
  "-5,10",
  "-5,11",
  "-5,12",
  "-5,13",
  "-5,14",
  "-5,15",
  "-5,16",
  "-5,17",
  "-5,18",
  "-5,19",
  "-5,20",
  "-5,21",
  "-5,22",
  "-5,23",
  "-5,24",
  "-5,25",
  "-5,26",
  "-5,27",
  "-4,-14",
  "-4,-13",
  "-4,-12",
  "-4,-11",
  "-4,-10",
  "-4,-9",
  "-4,-8",
  "-4,-7",
  "-4,-6",
  "-4,-5",
  "-4,-4",
  "-4,-3",
  "-4,-2",
  "-4,-1",
  "-4,0",
  "-4,1",
  "-4,2",
  "-4,3",
  "-4,4",
  "-4,5",
  "-4,6",
  "-4,7",
  "-4,8",
  "-4,9",
  "-4,10",
  "-4,11",
  "-4,12",
  "-4,13",
  "-4,14",
  "-4,15",
  "-4,16",
  "-4,17",
  "-4,18",
  "-4,19",
  "-4,20",
  "-4,21",
  "-4,22",
  "-4,23",
  "-4,24",
  "-4,25",
  "-4,26",
  "-4,27",
  "-3,-14",
  "-3,-13",
  "-3,-12",
  "-3,-11",
  "-3,-10",
  "-3,-9",
  "-3,-8",
  "-3,-7",
  "-3,-6",
  "-3,-5",
  "-3,-4",
  "-3,-3",
  "-3,-2",
  "-3,-1",
  "-3,0",
  "-3,1",
  "-3,2",
  "-3,3",
  "-3,4",
  "-3,5",
  "-3,6",
  "-3,7",
  "-3,8",
  "-3,9",
  "-3,10",
  "-3,11",
  "-3,12",
  "-3,13",
  "-3,14",
  "-3,15",
  "-3,16",
  "-3,17",
  "-3,18",
  "-3,19",
  "-3,20",
  "-3,21",
  "-3,22",
  "-3,23",
  "-3,24",
  "-3,25",
  "-3,26",
  "-3,27",
  "-2,-15",
  "-2,-14",
  "-2,-13",
  "-2,-12",
  "-2,-11",
  "-2,-10",
  "-2,-9",
  "-2,-8",
  "-2,-7",
  "-2,-6",
  "-2,-5",
  "-2,-4",
  "-2,-3",
  "-2,-2",
  "-2,-1",
  "-2,0",
  "-2,1",
  "-2,2",
  "-2,3",
  "-2,4",
  "-2,5",
  "-2,6",
  "-2,7",
  "-2,8",
  "-2,9",
  "-2,10",
  "-2,11",
  "-2,12",
  "-2,13",
  "-2,14",
  "-2,15",
  "-2,16",
  "-2,17",
  "-2,18",
  "-2,19",
  "-2,20",
  "-2,21",
  "-2,22",
  "-2,23",
  "-2,24",
  "-2,25",
  "-2,26",
  "-2,27",
  "-1,-17",
  "-1,-16",
  "-1,-15",
  "-1,-14",
  "-1,-13",
  "-1,-12",
  "-1,-11",
  "-1,-10",
  "-1,-9",
  "-1,-8",
  "-1,-7",
  "-1,-6",
  "-1,-5",
  "-1,-4",
  "-1,-3",
  "-1,-2",
  "-1,-1",
  "-1,0",
  "-1,1",
  "-1,2",
  "-1,3",
  "-1,4",
  "-1,5",
  "-1,6",
  "-1,7",
  "-1,8",
  "-1,9",
  "-1,10",
  "-1,11",
  "-1,12",
  "-1,13",
  "-1,14",
  "-1,15",
  "-1,16",
  "-1,17",
  "-1,18",
  "-1,19",
  "-1,20",
  "-1,21",
  "-1,22",
  "-1,23",
  "-1,24",
  "-1,25",
  "-1,26",
  "-1,27",
  "0,-17",
  "0,-16",
  "0,-15",
  "0,-14",
  "0,-13",
  "0,-12",
  "0,-11",
  "0,-10",
  "0,-9",
  "0,-8",
  "0,-7",
  "0,-6",
  "0,-5",
  "0,-4",
  "0,-3",
  "0,-2",
  "0,-1",
  "0,0",
  "0,1",
  "0,2",
  "0,3",
  "0,4",
  "0,5",
  "0,6",
  "0,7",
  "0,8",
  "0,9",
  "0,10",
  "0,11",
  "0,12",
  "0,13",
  "0,14",
  "0,15",
  "0,16",
  "0,17",
  "0,18",
  "0,19",
  "0,20",
  "0,21",
  "0,22",
  "0,23",
  "0,24",
  "0,25",
  "0,26",
  "0,27",
  "1,-17",
  "1,-16",
  "1,-15",
  "1,-14",
  "1,-13",
  "1,-12",
  "1,-11",
  "1,-10",
  "1,-9",
  "1,-8",
  "1,-7",
  "1,-6",
  "1,-5",
  "1,-4",
  "1,-3",
  "1,-2",
  "1,-1",
  "1,0",
  "1,1",
  "1,2",
  "1,3",
  "1,4",
  "1,5",
  "1,6",
  "1,7",
  "1,8",
  "1,9",
  "1,10",
  "1,11",
  "1,12",
  "1,13",
  "1,14",
  "1,15",
  "1,16",
  "1,17",
  "1,18",
  "1,19",
  "1,20",
  "1,21",
  "1,22",
  "1,23",
  "1,24",
  "1,25",
  "1,26",
  "1,27",
  "2,-17",
  "2,-16",
  "2,-15",
  "2,-14",
  "2,-13",
  "2,-12",
  "2,-11",
  "2,-10",
  "2,-9",
  "2,-8",
  "2,-7",
  "2,-6",
  "2,-5",
  "2,-4",
  "2,-3",
  "2,-2",
  "2,-1",
  "2,0",
  "2,1",
  "2,2",
  "2,3",
  "2,4",
  "2,5",
  "2,6",
  "2,7",
  "2,8",
  "2,9",
  "2,10",
  "2,11",
  "2,12",
  "2,13",
  "2,14",
  "2,15",
  "2,16",
  "2,17",
  "2,18",
  "2,19",
  "2,20",
  "2,21",
  "2,22",
  "2,23",
  "2,24",
  "2,25",
  "2,26",
  "3,-17",
  "3,-16",
  "3,-15",
  "3,-14",
  "3,-13",
  "3,-12",
  "3,-11",
  "3,-10",
  "3,-9",
  "3,-8",
  "3,-7",
  "3,-6",
  "3,-5",
  "3,-4",
  "3,-3",
  "3,-2",
  "3,-1",
  "3,0",
  "3,1",
  "3,2",
  "3,3",
  "3,4",
  "3,5",
  "3,6",
  "3,7",
  "3,8",
  "3,9",
  "3,10",
  "3,11",
  "3,12",
  "3,13",
  "3,14",
  "3,15",
  "3,16",
  "3,17",
  "3,18",
  "3,19",
  "3,20",
  "3,21",
  "3,22",
  "3,23",
  "3,24",
  "3,25",
  "3,26",
  "4,-17",
  "4,-16",
  "4,-15",
  "4,-14",
  "4,-13",
  "4,-12",
  "4,-11",
  "4,-10",
  "4,-9",
  "4,-8",
  "4,-7",
  "4,-6",
  "4,-5",
  "4,-4",
  "4,-3",
  "4,-2",
  "4,-1",
  "4,0",
  "4,1",
  "4,2",
  "4,3",
  "4,4",
  "4,5",
  "4,6",
  "4,7",
  "4,8",
  "4,9",
  "4,10",
  "4,11",
  "4,12",
  "4,13",
  "4,14",
  "4,15",
  "4,16",
  "4,17",
  "4,18",
  "4,19",
  "4,20",
  "4,21",
  "4,22",
  "4,23",
  "4,24",
  "4,25",
  "4,26",
  "5,-17",
  "5,-16",
  "5,-15",
  "5,-14",
  "5,-13",
  "5,-12",
  "5,-11",
  "5,-10",
  "5,-9",
  "5,-8",
  "5,-7",
  "5,-6",
  "5,-5",
  "5,-4",
  "5,-3",
  "5,-2",
  "5,-1",
  "5,0",
  "5,1",
  "5,2",
  "5,3",
  "5,4",
  "5,5",
  "5,6",
  "5,7",
  "5,8",
  "5,9",
  "5,10",
  "5,11",
  "5,12",
  "5,13",
  "5,14",
  "5,15",
  "5,16",
  "5,17",
  "5,18",
  "5,19",
  "5,20",
  "5,21",
  "5,22",
  "5,23",
  "5,24",
  "5,25",
  "5,26",
  "6,-18",
  "6,-17",
  "6,-16",
  "6,-15",
  "6,-14",
  "6,-13",
  "6,-12",
  "6,-11",
  "6,-10",
  "6,-9",
  "6,-8",
  "6,-7",
  "6,-6",
  "6,-5",
  "6,-4",
  "6,-3",
  "6,-2",
  "6,-1",
  "6,0",
  "6,1",
  "6,2",
  "6,3",
  "6,4",
  "6,5",
  "6,6",
  "6,7",
  "6,8",
  "6,9",
  "6,10",
  "6,11",
  "6,12",
  "6,13",
  "6,14",
  "6,15",
  "6,16",
  "6,17",
  "6,18",
  "6,19",
  "6,20",
  "6,21",
  "6,22",
  "6,23",
  "6,24",
  "6,25",
  "6,26",
  "7,-19",
  "7,-18",
  "7,-17",
  "7,-16",
  "7,-15",
  "7,-14",
  "7,-13",
  "7,-12",
  "7,-11",
  "7,-10",
  "7,-9",
  "7,-8",
  "7,-7",
  "7,-6",
  "7,-5",
  "7,-4",
  "7,-3",
  "7,-2",
  "7,-1",
  "7,0",
  "7,1",
  "7,2",
  "7,3",
  "7,4",
  "7,5",
  "7,6",
  "7,7",
  "7,8",
  "7,9",
  "7,10",
  "7,11",
  "7,12",
  "7,13",
  "7,14",
  "7,15",
  "7,16",
  "7,17",
  "7,18",
  "7,19",
  "7,20",
  "7,21",
  "7,22",
  "7,23",
  "7,24",
  "7,25",
  "7,26",
  "8,-19",
  "8,-18",
  "8,-17",
  "8,-16",
  "8,-15",
  "8,-14",
  "8,-13",
  "8,-12",
  "8,-11",
  "8,-10",
  "8,-9",
  "8,-8",
  "8,-7",
  "8,-6",
  "8,-5",
  "8,-4",
  "8,-3",
  "8,-2",
  "8,-1",
  "8,0",
  "8,1",
  "8,2",
  "8,3",
  "8,4",
  "8,5",
  "8,6",
  "8,7",
  "8,8",
  "8,9",
  "8,10",
  "8,11",
  "8,12",
  "8,13",
  "8,14",
  "8,15",
  "8,16",
  "8,17",
  "8,18",
  "8,19",
  "8,20",
  "8,21",
  "8,22",
  "8,23",
  "8,24",
  "8,25",
  "8,26",
  "9,-18",
  "9,-17",
  "9,-16",
  "9,-15",
  "9,-14",
  "9,-13",
  "9,-12",
  "9,-11",
  "9,-10",
  "9,-9",
  "9,-8",
  "9,-7",
  "9,-6",
  "9,-5",
  "9,-4",
  "9,-3",
  "9,-2",
  "9,-1",
  "9,0",
  "9,1",
  "9,2",
  "9,3",
  "9,4",
  "9,5",
  "9,6",
  "9,7",
  "9,8",
  "9,9",
  "9,10",
  "9,11",
  "9,12",
  "9,13",
  "9,14",
  "9,15",
  "9,16",
  "9,17",
  "9,18",
  "9,19",
  "9,20",
  "9,21",
  "9,22",
  "9,23",
  "9,24",
  "9,25",
  "9,26",
  "10,-18",
  "10,-17",
  "10,-16",
  "10,-15",
  "10,-14",
  "10,-13",
  "10,-12",
  "10,-11",
  "10,-10",
  "10,-9",
  "10,-8",
  "10,-7",
  "10,-6",
  "10,-5",
  "10,-4",
  "10,-3",
  "10,-2",
  "10,-1",
  "10,0",
  "10,1",
  "10,2",
  "10,3",
  "10,4",
  "10,5",
  "10,6",
  "10,7",
  "10,8",
  "10,9",
  "10,10",
  "10,11",
  "10,12",
  "10,13",
  "10,14",
  "10,15",
  "10,16",
  "10,17",
  "10,18",
  "10,19",
  "10,20",
  "10,21",
  "10,22",
  "10,23",
  "10,24",
  "10,25",
  "10,26",
  "11,-18",
  "11,-17",
  "11,-16",
  "11,-15",
  "11,-14",
  "11,-13",
  "11,-12",
  "11,-11",
  "11,-10",
  "11,-9",
  "11,-8",
  "11,-7",
  "11,-6",
  "11,-5",
  "11,-4",
  "11,-3",
  "11,-2",
  "11,-1",
  "11,0",
  "11,1",
  "11,2",
  "11,3",
  "11,4",
  "11,5",
  "11,6",
  "11,7",
  "11,8",
  "11,9",
  "11,10",
  "11,11",
  "11,12",
  "11,13",
  "11,14",
  "11,15",
  "11,16",
  "11,17",
  "11,18",
  "11,19",
  "11,20",
  "11,21",
  "11,22",
  "11,23",
  "12,-17",
  "12,-16",
  "12,-15",
  "12,-14",
  "12,-13",
  "12,-12",
  "12,-11",
  "12,-10",
  "12,-9",
  "12,-8",
  "12,-7",
  "12,-6",
  "12,-5",
  "12,-4",
  "12,-3",
  "12,-2",
  "12,-1",
  "12,0",
  "12,1",
  "12,2",
  "12,3",
  "12,4",
  "12,5",
  "12,6",
  "12,7",
  "12,8",
  "12,9",
  "12,10",
  "12,11",
  "12,12",
  "12,13",
  "12,14",
  "12,15",
  "12,16",
  "12,17",
  "12,18",
  "12,19",
  "12,20",
  "12,21",
  "12,22",
  "13,-17",
  "13,-16",
  "13,-15",
  "13,-14",
  "13,-13",
  "13,-12",
  "13,-11",
  "13,-10",
  "13,-9",
  "13,-8",
  "13,-7",
  "13,-6",
  "13,-5",
  "13,-4",
  "13,-3",
  "13,-2",
  "13,-1",
  "13,0",
  "13,1",
  "13,2",
  "13,3",
  "13,4",
  "13,5",
  "13,6",
  "13,7",
  "13,8",
  "13,9",
  "13,10",
  "13,11",
  "13,12",
  "13,13",
  "13,14",
  "13,15",
  "13,16",
  "13,17",
  "13,18",
  "13,19",
  "13,20",
  "13,21",
  "13,22",
  "14,-17",
  "14,-16",
  "14,-15",
  "14,-14",
  "14,-13",
  "14,-12",
  "14,-11",
  "14,-10",
  "14,-9",
  "14,-8",
  "14,-7",
  "14,-6",
  "14,-5",
  "14,-4",
  "14,-3",
  "14,-2",
  "14,-1",
  "14,0",
  "14,1",
  "14,2",
  "14,3",
  "14,4",
  "14,5",
  "14,6",
  "14,7",
  "14,8",
  "14,9",
  "14,10",
  "14,11",
  "14,12",
  "14,13",
  "14,14",
  "14,15",
  "14,16",
  "14,17",
  "14,18",
  "14,19",
  "14,20",
  "14,21",
  "14,22",
  "15,-17",
  "15,-16",
  "15,-15",
  "15,-14",
  "15,-13",
  "15,-12",
  "15,-11",
  "15,-10",
  "15,-9",
  "15,-8",
  "15,-7",
  "15,-6",
  "15,-5",
  "15,-4",
  "15,-3",
  "15,-2",
  "15,-1",
  "15,0",
  "15,1",
  "15,2",
  "15,3",
  "15,4",
  "15,5",
  "15,6",
  "15,7",
  "15,8",
  "15,9",
  "15,10",
  "15,11",
  "15,12",
  "15,13",
  "15,14",
  "15,15",
  "15,16",
  "15,17",
  "15,18",
  "16,-17",
  "16,-16",
  "16,-15",
  "16,-14",
  "16,-13",
  "16,-12",
  "16,-11",
  "16,-10",
  "16,-9",
  "16,-8",
  "16,-7",
  "16,-6",
  "16,-5",
  "16,-4",
  "16,-3",
  "16,-2",
  "16,-1",
  "16,0",
  "16,1",
  "16,2",
  "16,3",
  "16,4",
  "16,5",
  "16,6",
  "16,7",
  "16,8",
  "16,9",
  "16,10",
  "16,11",
  "16,12",
  "16,13",
  "16,14",
  "16,15",
  "16,16",
  "16,17",
  "17,-16",
  "17,-15",
  "17,-14",
  "17,-13",
  "17,-12",
  "17,-11",
  "17,-10",
  "17,-9",
  "17,-8",
  "17,-7",
  "17,-6",
  "17,-5",
  "17,-4",
  "17,-3",
  "17,-2",
  "17,-1",
  "17,0",
  "17,1",
  "17,2",
  "17,3",
  "17,4",
  "17,5",
  "17,6",
  "17,7",
  "17,8",
  "17,9",
  "17,10",
  "17,11",
  "17,12",
  "17,13",
  "17,14",
  "18,-16",
  "18,-15",
  "18,-14",
  "18,-13",
  "18,-12",
  "18,-11",
  "18,-10",
  "18,-9",
  "18,-8",
  "18,-7",
  "18,-6",
  "18,-5",
  "18,-4",
  "18,-3",
  "18,-2",
  "18,-1",
  "18,0",
  "18,1",
  "18,2",
  "18,3",
  "18,4",
  "18,5",
  "18,6",
  "18,7",
  "18,8",
  "18,9",
  "18,10",
  "18,11",
  "18,12",
  "18,13",
  "19,-12",
  "19,-11",
  "19,-10",
  "19,-9",
  "19,-8",
  "19,-7",
  "19,-6",
  "19,-5",
  "19,-4",
  "19,-3",
  "19,-2",
  "19,-1",
  "19,0",
  "19,1",
  "19,2",
  "19,3",
  "19,4",
  "19,5",
  "19,6",
  "19,7",
  "19,8",
  "19,9",
  "19,10",
  "19,11",
  "20,-12",
  "20,-11",
  "20,-10",
  "20,-9",
  "20,-8",
  "20,-7",
  "20,-6",
  "20,-5",
  "20,-4",
  "20,-3",
  "20,-2",
  "20,-1",
  "20,0",
  "20,1",
  "20,2",
  "20,3",
  "20,4",
  "20,5",
  "20,6",
  "20,7",
  "20,8",
  "20,9",
  "20,10",
  "21,-12",
  "21,-11",
  "21,-10",
  "21,-9",
  "21,-8",
  "21,-7",
  "21,-6",
  "21,-5",
  "21,-4",
  "21,-3",
  "21,-2",
  "21,-1",
  "21,0",
  "21,1",
  "21,2",
  "21,3",
  "21,4",
  "21,5",
  "21,6",
  "21,7",
  "21,8",
  "21,9",
  "21,10",
  "22,-12",
  "22,-11",
  "22,-10",
  "22,-9",
  "22,-8",
  "22,-7",
  "22,-6",
  "22,-5",
  "22,-4",
  "22,-3",
  "22,-2",
  "22,-1",
  "22,0",
  "22,1",
  "22,2",
  "22,3",
  "22,4",
  "22,5",
  "22,6",
  "22,7",
  "22,8",
  "23,-12",
  "23,-11",
  "23,-10",
  "23,-9",
  "23,-8",
  "23,-7",
  "23,-6",
  "23,-5",
  "23,-4",
  "23,-3",
  "23,-2",
  "23,-1",
  "23,0",
  "23,1",
  "23,2",
  "23,3",
  "23,4",
  "23,5",
  "23,6",
  "23,7",
])

export function isOfficialTes3Cell(
  interior: boolean,
  name: string,
  grid: { x: number; y: number } | null,
): boolean {
  return interior
    ? officialInteriorCells.has(name.toLocaleLowerCase("en-US"))
    : officialExteriorCells.has(`${grid?.x ?? 0},${grid?.y ?? 0}`)
}
